/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

import java.awt.Color;

/**
 *
 * @author Bhashitha
 */
public class Accomadation extends javax.swing.JFrame {

    /**
     * Creates new form Accomadation
     */
    public Accomadation() {
        initComponents();
         pnlpc1.setBackground(new Color(0,0,0,200));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlpc1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblID = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        txtHname = new javax.swing.JTextField();
        lblHname = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        txtHaddress = new javax.swing.JTextField();
        lblHaddress = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        txtMname = new javax.swing.JTextField();
        lblMname = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        txtCnum = new javax.swing.JTextField();
        lblCnum = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        txtstar = new javax.swing.JTextField();
        lblname5 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        lblstar = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        lblexit = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlpc1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel5.setFont(new java.awt.Font("Segoe UI Emoji", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("ACCOMADATION");

        jLabel6.setFont(new java.awt.Font("Ink Free", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("    We  make a better journey for you!");

        javax.swing.GroupLayout pnlpc1Layout = new javax.swing.GroupLayout(pnlpc1);
        pnlpc1.setLayout(pnlpc1Layout);
        pnlpc1Layout.setHorizontalGroup(
            pnlpc1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlpc1Layout.createSequentialGroup()
                .addGroup(pnlpc1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlpc1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlpc1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlpc1Layout.setVerticalGroup(
            pnlpc1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlpc1Layout.createSequentialGroup()
                .addGap(191, 191, 191)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(531, Short.MAX_VALUE))
        );

        getContentPane().add(pnlpc1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, 830));

        jLabel1.setIcon(new javax.swing.ImageIcon("D:\\LMS\\2nd year\\1st Sem\\java\\Coursework\\Project\\src\\project\\Images\\ea1fbb41c96075590669ee2d3fcda883.jpg")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, 830));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lblID.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        lblID.setForeground(new java.awt.Color(51, 51, 51));
        lblID.setText("Registration ID");

        txtID.setBackground(new java.awt.Color(255, 255, 255));
        txtID.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 14)); // NOI18N
        txtID.setForeground(new java.awt.Color(0, 102, 204));
        txtID.setBorder(null);
        txtID.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtIDFocusGained(evt);
            }
        });

        jSeparator1.setBackground(new java.awt.Color(204, 204, 204));

        txtHname.setBackground(new java.awt.Color(255, 255, 255));
        txtHname.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 14)); // NOI18N
        txtHname.setForeground(new java.awt.Color(0, 102, 204));
        txtHname.setBorder(null);
        txtHname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtHnameFocusGained(evt);
            }
        });

        lblHname.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        lblHname.setForeground(new java.awt.Color(51, 51, 51));
        lblHname.setText("Hotel Name");

        jSeparator2.setBackground(new java.awt.Color(204, 204, 204));

        txtHaddress.setBackground(new java.awt.Color(255, 255, 255));
        txtHaddress.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 14)); // NOI18N
        txtHaddress.setForeground(new java.awt.Color(0, 102, 204));
        txtHaddress.setBorder(null);
        txtHaddress.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtHaddressFocusGained(evt);
            }
        });

        lblHaddress.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        lblHaddress.setForeground(new java.awt.Color(51, 51, 51));
        lblHaddress.setText("Address");

        jSeparator3.setBackground(new java.awt.Color(204, 204, 204));

        txtMname.setBackground(new java.awt.Color(255, 255, 255));
        txtMname.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 14)); // NOI18N
        txtMname.setForeground(new java.awt.Color(0, 102, 204));
        txtMname.setBorder(null);
        txtMname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtMnameFocusGained(evt);
            }
        });

        lblMname.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        lblMname.setForeground(new java.awt.Color(51, 51, 51));
        lblMname.setText("Manager Name");

        jSeparator4.setBackground(new java.awt.Color(204, 204, 204));

        txtCnum.setBackground(new java.awt.Color(255, 255, 255));
        txtCnum.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 14)); // NOI18N
        txtCnum.setForeground(new java.awt.Color(0, 102, 204));
        txtCnum.setBorder(null);
        txtCnum.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCnumFocusGained(evt);
            }
        });

        lblCnum.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        lblCnum.setForeground(new java.awt.Color(51, 51, 51));
        lblCnum.setText("Contact No:");

        jSeparator5.setBackground(new java.awt.Color(204, 204, 204));

        txtstar.setBackground(new java.awt.Color(255, 255, 255));
        txtstar.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 14)); // NOI18N
        txtstar.setForeground(new java.awt.Color(0, 102, 204));
        txtstar.setBorder(null);
        txtstar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtstarFocusGained(evt);
            }
        });

        lblname5.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        lblname5.setForeground(new java.awt.Color(51, 51, 51));
        lblname5.setText("Facility");

        jSeparator6.setBackground(new java.awt.Color(204, 204, 204));

        lblstar.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        lblstar.setForeground(new java.awt.Color(51, 51, 51));
        lblstar.setText("Star Level (star)");

        jCheckBox1.setText("AC/Non-AC");

        jCheckBox2.setText("Pool Facility");

        jCheckBox3.setText("Drivers Quaters");

        jCheckBox4.setText("Wi-Fi");

        jCheckBox5.setText("Lanuage Preference");

        jButton1.setBackground(new java.awt.Color(0, 51, 153));
        jButton1.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Submit");
        jButton1.setBorder(null);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lblexit.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        lblexit.setForeground(new java.awt.Color(0, 51, 153));
        lblexit.setText("x");
        lblexit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblexit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblexitMousePressed(evt);
            }
        });

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/Icons/icons8-back-arrow-24.png"))); // NOI18N
        jButton4.setBorder(null);
        jButton4.setBorderPainted(false);
        jButton4.setContentAreaFilled(false);
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(lblHname, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jSeparator2)
                                        .addComponent(txtHname, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jSeparator1)
                                        .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblID, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jButton4)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblexit))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCheckBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jCheckBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblstar, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jSeparator6)
                                        .addComponent(txtstar, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jSeparator5)
                                        .addComponent(txtCnum, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblCnum, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jSeparator4)
                                        .addComponent(txtMname, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblMname, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(lblHaddress, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jSeparator3)
                                        .addComponent(txtHaddress, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jCheckBox3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jCheckBox5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE))
                                    .addComponent(jCheckBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblname5, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(62, 62, 62)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 70, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton4)
                    .addComponent(lblexit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblID)
                .addGap(12, 12, 12)
                .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblHname)
                .addGap(12, 12, 12)
                .addComponent(txtHname, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblHaddress)
                .addGap(12, 12, 12)
                .addComponent(txtHaddress, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblMname)
                .addGap(12, 12, 12)
                .addComponent(txtMname, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblCnum)
                .addGap(12, 12, 12)
                .addComponent(txtCnum, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblstar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtstar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblname5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, 520, 830));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIDFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtIDFocusGained
        // TODO add your handling code here:
        lblID.setForeground(new Color(0,51,153));
        txtID.setForeground(new Color(0,51,153));
        lblHname.setForeground(new Color(60,63,65));
        txtHname.setForeground(new Color(60,63,65));
        lblHaddress.setForeground(new Color(60,63,65));
        txtHaddress.setForeground(new Color(60,63,65));
        lblMname.setForeground(new Color(60,63,65));
        txtMname.setForeground(new Color(60,63,65));
        lblCnum.setForeground(new Color(60,63,65));
        txtCnum.setForeground(new Color(60,63,65));
        lblstar.setForeground(new Color(60,63,65));
        txtstar.setForeground(new Color(60,63,65));

    }//GEN-LAST:event_txtIDFocusGained

    private void txtHnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtHnameFocusGained
        // TODO add your handling code here:
        lblHname.setForeground(new Color(0,51,153));
        txtHname.setForeground(new Color(0,51,153));
        lblID.setForeground(new Color(60,63,65));
        txtID.setForeground(new Color(60,63,65));
        lblHaddress.setForeground(new Color(60,63,65));
        txtHaddress.setForeground(new Color(60,63,65));
        lblMname.setForeground(new Color(60,63,65));
        txtMname.setForeground(new Color(60,63,65));
        lblCnum.setForeground(new Color(60,63,65));
        txtCnum.setForeground(new Color(60,63,65));
        lblstar.setForeground(new Color(60,63,65));
        txtstar.setForeground(new Color(60,63,65));
    }//GEN-LAST:event_txtHnameFocusGained

    private void txtHaddressFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtHaddressFocusGained
        // TODO add your handling code here:
        lblHaddress.setForeground(new Color(0,51,153));
        txtHaddress.setForeground(new Color(0,51,153));
        lblID.setForeground(new Color(60,63,65));
        txtID.setForeground(new Color(60,63,65));
        lblHname.setForeground(new Color(60,63,65));
        txtHname.setForeground(new Color(60,63,65));
        lblMname.setForeground(new Color(60,63,65));
        txtMname.setForeground(new Color(60,63,65));
        lblCnum.setForeground(new Color(60,63,65));
        txtCnum.setForeground(new Color(60,63,65));
        lblstar.setForeground(new Color(60,63,65));
        txtstar.setForeground(new Color(60,63,65));
    }//GEN-LAST:event_txtHaddressFocusGained

    private void txtMnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMnameFocusGained
        // TODO add your handling code here:
        lblMname.setForeground(new Color(0,51,153));
        txtMname.setForeground(new Color(0,51,153));
        lblID.setForeground(new Color(60,63,65));
        txtID.setForeground(new Color(60,63,65));
        lblHaddress.setForeground(new Color(60,63,65));
        txtHaddress.setForeground(new Color(60,63,65));
        lblHname.setForeground(new Color(60,63,65));
        txtHname.setForeground(new Color(60,63,65));
        lblCnum.setForeground(new Color(60,63,65));
        txtCnum.setForeground(new Color(60,63,65));
        lblstar.setForeground(new Color(60,63,65));
        txtstar.setForeground(new Color(60,63,65));
    }//GEN-LAST:event_txtMnameFocusGained

    private void txtCnumFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCnumFocusGained
        // TODO add your handling code here:
        lblCnum.setForeground(new Color(0,51,153));
        txtCnum.setForeground(new Color(0,51,153));
        lblID.setForeground(new Color(60,63,65));
        txtID.setForeground(new Color(60,63,65));
        lblHaddress.setForeground(new Color(60,63,65));
        txtHaddress.setForeground(new Color(60,63,65));
        lblMname.setForeground(new Color(60,63,65));
        txtMname.setForeground(new Color(60,63,65));
        lblHname.setForeground(new Color(60,63,65));
        txtHname.setForeground(new Color(60,63,65));
        lblstar.setForeground(new Color(60,63,65));
        txtstar.setForeground(new Color(60,63,65));
    }//GEN-LAST:event_txtCnumFocusGained

    private void txtstarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtstarFocusGained
        // TODO add your handling code here:
        lblstar.setForeground(new Color(0,51,153));
        txtstar.setForeground(new Color(0,51,153));
        lblID.setForeground(new Color(60,63,65));
        txtID.setForeground(new Color(60,63,65));
        lblHaddress.setForeground(new Color(60,63,65));
        txtHaddress.setForeground(new Color(60,63,65));
        lblMname.setForeground(new Color(60,63,65));
        txtMname.setForeground(new Color(60,63,65));
        lblCnum.setForeground(new Color(60,63,65));
        txtCnum.setForeground(new Color(60,63,65));
        lblHname.setForeground(new Color(60,63,65));
        txtHname.setForeground(new Color(60,63,65));
    }//GEN-LAST:event_txtstarFocusGained

    private void lblexitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblexitMousePressed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_lblexitMousePressed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        Home t2=new  Home ();
        t2.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Accomadation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Accomadation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Accomadation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Accomadation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Accomadation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JLabel lblCnum;
    private javax.swing.JLabel lblHaddress;
    private javax.swing.JLabel lblHname;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblMname;
    private javax.swing.JLabel lblexit;
    private javax.swing.JLabel lblname5;
    private javax.swing.JLabel lblstar;
    private javax.swing.JPanel pnlpc1;
    private javax.swing.JTextField txtCnum;
    private javax.swing.JTextField txtHaddress;
    private javax.swing.JTextField txtHname;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtMname;
    private javax.swing.JTextField txtstar;
    // End of variables declaration//GEN-END:variables
}
