/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

import java.awt.Color;

/**
 *
 * @author Bhashitha
 */
public class SignUp extends javax.swing.JFrame {

    /**
     * Creates new form SignUp
     */
    public SignUp() {
        initComponents();
        pnlsign.setBackground(new Color(0,0,0,200));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        lblln = new javax.swing.JLabel();
        txtfn = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        lbluser = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        lblmail = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        lblpass = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        txtpass = new javax.swing.JPasswordField();
        lblfn = new javax.swing.JLabel();
        lblcpass = new javax.swing.JLabel();
        txtln = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        lblexit1 = new javax.swing.JLabel();
        txtmail = new javax.swing.JTextField();
        txtuname = new javax.swing.JTextField();
        txtcpass = new javax.swing.JPasswordField();
        jButton4 = new javax.swing.JButton();
        pnlsign = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(5, 6, 40));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setForeground(new java.awt.Color(0, 0, 0));

        lblln.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        lblln.setForeground(new java.awt.Color(51, 51, 51));
        lblln.setText("Last Name");

        txtfn.setBackground(new java.awt.Color(255, 255, 255));
        txtfn.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 14)); // NOI18N
        txtfn.setForeground(new java.awt.Color(0, 102, 204));
        txtfn.setBorder(null);
        txtfn.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtfnFocusGained(evt);
            }
        });

        jSeparator1.setBackground(new java.awt.Color(204, 204, 204));

        lbluser.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        lbluser.setForeground(new java.awt.Color(51, 51, 51));
        lbluser.setText("Username");

        jSeparator2.setBackground(new java.awt.Color(204, 204, 204));

        lblmail.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        lblmail.setForeground(new java.awt.Color(51, 51, 51));
        lblmail.setText("Email");

        jSeparator3.setBackground(new java.awt.Color(204, 204, 204));

        lblpass.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        lblpass.setForeground(new java.awt.Color(51, 51, 51));
        lblpass.setText("Password");

        jSeparator4.setBackground(new java.awt.Color(204, 204, 204));

        jSeparator5.setBackground(new java.awt.Color(204, 204, 204));

        txtpass.setBackground(new java.awt.Color(255, 255, 255));
        txtpass.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 14)); // NOI18N
        txtpass.setForeground(new java.awt.Color(0, 102, 204));
        txtpass.setBorder(null);
        txtpass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtpassFocusGained(evt);
            }
        });

        lblfn.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        lblfn.setForeground(new java.awt.Color(51, 51, 51));
        lblfn.setText("First Name");

        lblcpass.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        lblcpass.setForeground(new java.awt.Color(51, 51, 51));
        lblcpass.setText("Confirm Password");

        txtln.setBackground(new java.awt.Color(255, 255, 255));
        txtln.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 14)); // NOI18N
        txtln.setForeground(new java.awt.Color(0, 102, 204));
        txtln.setBorder(null);
        txtln.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtlnFocusGained(evt);
            }
        });

        jSeparator6.setBackground(new java.awt.Color(204, 204, 204));

        jButton1.setBackground(new java.awt.Color(0, 51, 153));
        jButton1.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Signup");
        jButton1.setBorder(null);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lblexit1.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        lblexit1.setForeground(new java.awt.Color(0, 51, 153));
        lblexit1.setText("x");
        lblexit1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblexit1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblexit1MousePressed(evt);
            }
        });

        txtmail.setBackground(new java.awt.Color(255, 255, 255));
        txtmail.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 14)); // NOI18N
        txtmail.setForeground(new java.awt.Color(0, 102, 204));
        txtmail.setBorder(null);
        txtmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtmailFocusGained(evt);
            }
        });

        txtuname.setBackground(new java.awt.Color(255, 255, 255));
        txtuname.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 14)); // NOI18N
        txtuname.setForeground(new java.awt.Color(0, 102, 204));
        txtuname.setBorder(null);
        txtuname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtunameFocusGained(evt);
            }
        });

        txtcpass.setBackground(new java.awt.Color(255, 255, 255));
        txtcpass.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 14)); // NOI18N
        txtcpass.setForeground(new java.awt.Color(0, 102, 204));
        txtcpass.setBorder(null);
        txtcpass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtcpassFocusGained(evt);
            }
        });

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/Icons/icons8-back-arrow-24.png"))); // NOI18N
        jButton4.setBorder(null);
        jButton4.setBorderPainted(false);
        jButton4.setContentAreaFilled(false);
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtuname, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtcpass, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtmail, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblfn, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtln, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jSeparator2)
                                .addComponent(lbluser, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtfn, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblln, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblmail, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jSeparator5)
                                .addComponent(txtpass, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblpass, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblcpass))
                        .addGap(71, 71, 71)
                        .addComponent(lblexit1)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(lblfn))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jButton4)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtfn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(lblln)
                        .addGap(10, 10, 10)
                        .addComponent(txtln, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(lbluser)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtuname, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblexit1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(lblmail)
                .addGap(10, 10, 10)
                .addComponent(txtmail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(lblpass)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtpass, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(lblcpass)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtcpass, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 0, 500, 790));

        jLabel2.setFont(new java.awt.Font("Segoe UI Emoji", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("SIGNUP");

        jLabel3.setFont(new java.awt.Font("Ink Free", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("    We  make a better journey for you!");

        javax.swing.GroupLayout pnlsignLayout = new javax.swing.GroupLayout(pnlsign);
        pnlsign.setLayout(pnlsignLayout);
        pnlsignLayout.setHorizontalGroup(
            pnlsignLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 340, Short.MAX_VALUE)
            .addGroup(pnlsignLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlsignLayout.createSequentialGroup()
                    .addGap(0, 25, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 25, Short.MAX_VALUE))
                .addGroup(pnlsignLayout.createSequentialGroup()
                    .addGap(77, 77, 77)
                    .addComponent(jLabel2)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        pnlsignLayout.setVerticalGroup(
            pnlsignLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 790, Short.MAX_VALUE)
            .addGroup(pnlsignLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlsignLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(pnlsignLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(pnlsignLayout.createSequentialGroup()
                            .addGap(70, 70, 70)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        getContentPane().add(pnlsign, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 790));

        jLabel1.setIcon(new javax.swing.ImageIcon("D:\\LMS\\2nd year\\1st Sem\\java\\Coursework\\Project\\src\\project\\Images\\castlereagh-resevoir-sri-lanka-SRILANKA0618.jpg")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 790));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtfnFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtfnFocusGained
        // TODO add your handling code here:
        lblfn.setForeground(new Color(0,51,153));
        jSeparator1.setBackground(new Color(0,51,153));
        jSeparator2.setForeground(new Color(60,63,65));
        jSeparator3.setForeground(new Color(60,63,65));
        jSeparator4.setForeground(new Color(60,63,65));
        jSeparator5.setForeground(new Color(60,63,65));
        jSeparator6.setForeground(new Color(60,63,65));
        lbluser.setForeground(new Color(60,63,65));
        lblmail.setForeground(new Color(60,63,65));
        lblpass.setForeground(new Color(60,63,65));
        lblcpass.setForeground(new Color(60,63,65));
        txtfn.setForeground(new Color(0,51,153));
        txtln.setForeground(new Color(60,63,65));
        txtuname.setForeground(new Color(60,63,65));
        txtmail.setForeground(new Color(60,63,65));
        txtpass.setForeground(new Color(60,63,65));
        txtln.setForeground(new Color(60,63,65));
        
        

    }//GEN-LAST:event_txtfnFocusGained

    private void txtpassFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtpassFocusGained
        // TODO add your handling code here:
        lblpass.setForeground(new Color(0,51,153));
        jSeparator1.setBackground(new Color(0,51,153));
        jSeparator2.setForeground(new Color(60,63,65));
        jSeparator3.setForeground(new Color(60,63,65));
        jSeparator4.setForeground(new Color(60,63,65));
        jSeparator5.setForeground(new Color(60,63,65));
        jSeparator6.setForeground(new Color(60,63,65));
        lbluser.setForeground(new Color(60,63,65));
        lblmail.setForeground(new Color(60,63,65));
        lblfn.setForeground(new Color(60,63,65));
        lblcpass.setForeground(new Color(60,63,65));
        txtpass.setForeground(new Color(0,51,153));
        txtln.setForeground(new Color(60,63,65));
        txtuname.setForeground(new Color(60,63,65));
        txtmail.setForeground(new Color(60,63,65));
        txtfn.setForeground(new Color(60,63,65));
        txtln.setForeground(new Color(60,63,65));
    }//GEN-LAST:event_txtpassFocusGained

    private void txtlnFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtlnFocusGained
        // TODO add your handling code here:
        lblln.setForeground(new Color(0,51,153));
        jSeparator6.setBackground(new Color(0,51,153));
        jSeparator2.setForeground(new Color(60,63,65));
        jSeparator3.setForeground(new Color(60,63,65));
        jSeparator4.setForeground(new Color(60,63,65));
        jSeparator5.setForeground(new Color(60,63,65));
        jSeparator1.setForeground(new Color(60,63,65));
        lbluser.setForeground(new Color(60,63,65));
        lblmail.setForeground(new Color(60,63,65));
        lblpass.setForeground(new Color(60,63,65));
        lblfn.setForeground(new Color(60,63,65));
        txtln.setForeground(new Color(0,51,153));
        txtuname.setForeground(new Color(60,63,65));
        txtmail.setForeground(new Color(60,63,65));
        txtpass.setForeground(new Color(60,63,65));
        txtfn.setForeground(new Color(60,63,65));

    }//GEN-LAST:event_txtlnFocusGained

    private void lblexit1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblexit1MousePressed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_lblexit1MousePressed

    private void txtmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtmailFocusGained
        // TODO add your handling code here:
        lblmail.setForeground(new Color(0,51,153));
        jSeparator6.setBackground(new Color(0,51,153));
        jSeparator2.setForeground(new Color(60,63,65));
        jSeparator3.setForeground(new Color(60,63,65));
        jSeparator4.setForeground(new Color(60,63,65));
        jSeparator5.setForeground(new Color(60,63,65));
        jSeparator1.setForeground(new Color(60,63,65));
        lbluser.setForeground(new Color(60,63,65));
        lblln.setForeground(new Color(60,63,65));
        lblpass.setForeground(new Color(60,63,65));
        lblfn.setForeground(new Color(60,63,65));
        txtmail.setForeground(new Color(0,51,153));
        txtuname.setForeground(new Color(60,63,65));
        txtln.setForeground(new Color(60,63,65));
        txtpass.setForeground(new Color(60,63,65));
        txtfn.setForeground(new Color(60,63,65));
    }//GEN-LAST:event_txtmailFocusGained

    private void txtunameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtunameFocusGained
        // TODO add your handling code here:
        lbluser.setForeground(new Color(0,51,153));
        jSeparator6.setBackground(new Color(0,51,153));
        jSeparator2.setForeground(new Color(60,63,65));
        jSeparator3.setForeground(new Color(60,63,65));
        jSeparator4.setForeground(new Color(60,63,65));
        jSeparator5.setForeground(new Color(60,63,65));
        jSeparator1.setForeground(new Color(60,63,65));
        lblfn.setForeground(new Color(60,63,65));
        lblln.setForeground(new Color(60,63,65));
        lblmail.setForeground(new Color(60,63,65));
        lblpass.setForeground(new Color(60,63,65));
        txtuname.setForeground(new Color(0,51,153));
        txtln.setForeground(new Color(60,63,65));
        txtmail.setForeground(new Color(60,63,65));
        txtpass.setForeground(new Color(60,63,65));
        txtfn.setForeground(new Color(60,63,65));
    }//GEN-LAST:event_txtunameFocusGained

    private void txtcpassFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtcpassFocusGained
        // TODO add your handling code here:
        lblcpass.setForeground(new Color(0,51,153));
        jSeparator6.setBackground(new Color(0,51,153));
        jSeparator2.setForeground(new Color(60,63,65));
        jSeparator3.setForeground(new Color(60,63,65));
        jSeparator4.setForeground(new Color(60,63,65));
        jSeparator5.setForeground(new Color(60,63,65));
        jSeparator1.setForeground(new Color(60,63,65));
        lblfn.setForeground(new Color(60,63,65));
        lblln.setForeground(new Color(60,63,65));
        lblmail.setForeground(new Color(60,63,65));
        lblpass.setForeground(new Color(60,63,65));
        txtcpass.setForeground(new Color(0,51,153));
        txtln.setForeground(new Color(60,63,65));
        txtmail.setForeground(new Color(60,63,65));
        txtpass.setForeground(new Color(60,63,65));
        txtfn.setForeground(new Color(60,63,65));
        txtuname.setForeground(new Color(60,63,65));
    }//GEN-LAST:event_txtcpassFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JLabel lblcpass;
    private javax.swing.JLabel lblexit1;
    private javax.swing.JLabel lblfn;
    private javax.swing.JLabel lblln;
    private javax.swing.JLabel lblmail;
    private javax.swing.JLabel lblpass;
    private javax.swing.JLabel lbluser;
    private javax.swing.JPanel pnlsign;
    private javax.swing.JPasswordField txtcpass;
    private javax.swing.JTextField txtfn;
    private javax.swing.JTextField txtln;
    private javax.swing.JTextField txtmail;
    private javax.swing.JPasswordField txtpass;
    private javax.swing.JTextField txtuname;
    // End of variables declaration//GEN-END:variables
}
