/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

import java.awt.Color;

/**
 *
 * @author Bhashitha
 */
public class Traveller_1 extends javax.swing.JFrame {

    /**
     * Creates new form Traveller
     */
    public Traveller_1() {
        initComponents();
        jPanel1.setBackground(new Color(0,0,0,200));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        lblln = new javax.swing.JLabel();
        txtfn = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        lblcountry = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        lblnic = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        lblfn = new javax.swing.JLabel();
        txtln = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        lblexit1 = new javax.swing.JLabel();
        txtnic = new javax.swing.JTextField();
        txtcountry = new javax.swing.JTextField();
        txtpassport = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        lblpassport = new javax.swing.JLabel();
        txtmail = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        lblmail = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setForeground(new java.awt.Color(0, 0, 0));

        lblln.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        lblln.setForeground(new java.awt.Color(51, 51, 51));
        lblln.setText("Last Name");

        txtfn.setBackground(new java.awt.Color(255, 255, 255));
        txtfn.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 14)); // NOI18N
        txtfn.setForeground(new java.awt.Color(0, 102, 204));
        txtfn.setBorder(null);
        txtfn.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtfnFocusGained(evt);
            }
        });

        jSeparator1.setBackground(new java.awt.Color(204, 204, 204));

        lblcountry.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        lblcountry.setForeground(new java.awt.Color(51, 51, 51));
        lblcountry.setText("Country Origin");

        jSeparator2.setBackground(new java.awt.Color(204, 204, 204));

        lblnic.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        lblnic.setForeground(new java.awt.Color(51, 51, 51));
        lblnic.setText("NIC");

        jSeparator3.setBackground(new java.awt.Color(204, 204, 204));

        jSeparator4.setBackground(new java.awt.Color(204, 204, 204));

        lblfn.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        lblfn.setForeground(new java.awt.Color(51, 51, 51));
        lblfn.setText("First Name");

        txtln.setBackground(new java.awt.Color(255, 255, 255));
        txtln.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 14)); // NOI18N
        txtln.setForeground(new java.awt.Color(0, 102, 204));
        txtln.setBorder(null);
        txtln.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtlnFocusGained(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(0, 51, 153));
        jButton1.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Next Page");
        jButton1.setBorder(null);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        lblexit1.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        lblexit1.setForeground(new java.awt.Color(0, 51, 153));
        lblexit1.setText("x");
        lblexit1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblexit1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblexit1MousePressed(evt);
            }
        });

        txtnic.setBackground(new java.awt.Color(255, 255, 255));
        txtnic.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 14)); // NOI18N
        txtnic.setForeground(new java.awt.Color(0, 102, 204));
        txtnic.setBorder(null);
        txtnic.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtnicFocusGained(evt);
            }
        });

        txtcountry.setBackground(new java.awt.Color(255, 255, 255));
        txtcountry.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 14)); // NOI18N
        txtcountry.setForeground(new java.awt.Color(0, 102, 204));
        txtcountry.setBorder(null);
        txtcountry.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtcountryFocusGained(evt);
            }
        });

        txtpassport.setBackground(new java.awt.Color(255, 255, 255));
        txtpassport.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 14)); // NOI18N
        txtpassport.setForeground(new java.awt.Color(0, 102, 204));
        txtpassport.setBorder(null);
        txtpassport.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtpassportFocusGained(evt);
            }
        });

        jSeparator5.setBackground(new java.awt.Color(204, 204, 204));

        lblpassport.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        lblpassport.setForeground(new java.awt.Color(51, 51, 51));
        lblpassport.setText("Passport No");

        txtmail.setBackground(new java.awt.Color(255, 255, 255));
        txtmail.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 14)); // NOI18N
        txtmail.setForeground(new java.awt.Color(0, 102, 204));
        txtmail.setBorder(null);
        txtmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtmailFocusGained(evt);
            }
        });

        jSeparator6.setBackground(new java.awt.Color(204, 204, 204));

        lblmail.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        lblmail.setForeground(new java.awt.Color(51, 51, 51));
        lblmail.setText("E Mail");

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/Icons/icons8-back-arrow-24.png"))); // NOI18N
        jButton2.setBorder(null);
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtmail, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblmail, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtpassport, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblpassport, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtcountry, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtnic, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblfn, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtln, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jSeparator2)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtfn, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblln, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblcountry, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblnic, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(71, 71, 71)
                        .addComponent(lblexit1)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(lblfn))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jButton2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtfn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(lblln)
                        .addGap(10, 10, 10)
                        .addComponent(txtln, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(lblcountry)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtcountry, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblexit1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(lblnic)
                .addGap(10, 10, 10)
                .addComponent(txtnic, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(lblpassport)
                .addGap(10, 10, 10)
                .addComponent(txtpassport, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(lblmail)
                .addGap(10, 10, 10)
                .addComponent(txtmail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 0, 490, 800));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel3.setFont(new java.awt.Font("Ink Free", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("    We  make a better journey for you!");

        jLabel2.setFont(new java.awt.Font("Segoe UI Emoji", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("TRAVELLER");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jLabel2)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(272, 272, 272)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(431, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 800));

        jLabel1.setIcon(new javax.swing.ImageIcon("D:\\LMS\\2nd year\\1st Sem\\java\\Coursework\\Project\\src\\project\\Images\\5.jpg")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 800));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtfnFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtfnFocusGained
        // TODO add your handling code here:
        lblfn.setForeground(new Color(0,51,153));
        jSeparator6.setBackground(new Color(0,51,153));
        jSeparator2.setForeground(new Color(60,63,65));
        jSeparator3.setForeground(new Color(60,63,65));
        jSeparator4.setForeground(new Color(60,63,65));
        jSeparator5.setForeground(new Color(60,63,65));
        jSeparator1.setForeground(new Color(60,63,65));
        lblmail.setForeground(new Color(60,63,65));
         lblcountry.setForeground(new Color(60,63,65));
        lblln.setForeground(new Color(60,63,65));
        lblnic.setForeground(new Color(60,63,65));
        lblpassport.setForeground(new Color(60,63,65));
        txtfn.setForeground(new Color(0,51,153));
        txtln.setForeground(new Color(60,63,65));
        txtnic.setForeground(new Color(60,63,65));
        txtpassport.setForeground(new Color(60,63,65));
        txtmail.setForeground(new Color(60,63,65));
        txtcountry.setForeground(new Color(60,63,65));

    }//GEN-LAST:event_txtfnFocusGained

    private void txtlnFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtlnFocusGained
        // TODO add your handling code here:
       lblln.setForeground(new Color(0,51,153));
        jSeparator6.setBackground(new Color(0,51,153));
        jSeparator2.setForeground(new Color(60,63,65));
        jSeparator3.setForeground(new Color(60,63,65));
        jSeparator4.setForeground(new Color(60,63,65));
        jSeparator5.setForeground(new Color(60,63,65));
        jSeparator1.setForeground(new Color(60,63,65));
        lblfn.setForeground(new Color(60,63,65));
        lblmail.setForeground(new Color(60,63,65));
        lblnic.setForeground(new Color(60,63,65));
        lblpassport.setForeground(new Color(60,63,65));
         lblcountry.setForeground(new Color(60,63,65));
        txtln.setForeground(new Color(0,51,153));
        txtmail.setForeground(new Color(60,63,65));
        txtnic.setForeground(new Color(60,63,65));
        txtpassport.setForeground(new Color(60,63,65));
        txtfn.setForeground(new Color(60,63,65));
        txtcountry.setForeground(new Color(60,63,65));
    }//GEN-LAST:event_txtlnFocusGained

    private void lblexit1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblexit1MousePressed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_lblexit1MousePressed

    private void txtnicFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtnicFocusGained
        // TODO add your handling code here:
       lblnic.setForeground(new Color(0,51,153));
        jSeparator6.setBackground(new Color(0,51,153));
        jSeparator2.setForeground(new Color(60,63,65));
        jSeparator3.setForeground(new Color(60,63,65));
        jSeparator4.setForeground(new Color(60,63,65));
        jSeparator5.setForeground(new Color(60,63,65));
        jSeparator1.setForeground(new Color(60,63,65));
        lblfn.setForeground(new Color(60,63,65));
        lblln.setForeground(new Color(60,63,65));
        lblmail.setForeground(new Color(60,63,65));
        lblpassport.setForeground(new Color(60,63,65));
         lblcountry.setForeground(new Color(60,63,65));
        txtnic.setForeground(new Color(0,51,153));
        txtln.setForeground(new Color(60,63,65));
        txtmail.setForeground(new Color(60,63,65));
        txtpassport.setForeground(new Color(60,63,65));
        txtfn.setForeground(new Color(60,63,65));
        txtcountry.setForeground(new Color(60,63,65));
    }//GEN-LAST:event_txtnicFocusGained

    private void txtcountryFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtcountryFocusGained
        // TODO add your handling code here:
        lblcountry.setForeground(new Color(0,51,153));
        jSeparator6.setBackground(new Color(0,51,153));
        jSeparator2.setForeground(new Color(60,63,65));
        jSeparator3.setForeground(new Color(60,63,65));
        jSeparator4.setForeground(new Color(60,63,65));
        jSeparator5.setForeground(new Color(60,63,65));
        jSeparator1.setForeground(new Color(60,63,65));
        lblfn.setForeground(new Color(60,63,65));
        lblln.setForeground(new Color(60,63,65));
        lblnic.setForeground(new Color(60,63,65));
        lblpassport.setForeground(new Color(60,63,65));
         lblmail.setForeground(new Color(60,63,65));
        txtcountry.setForeground(new Color(0,51,153));
        txtln.setForeground(new Color(60,63,65));
        txtnic.setForeground(new Color(60,63,65));
        txtpassport.setForeground(new Color(60,63,65));
        txtfn.setForeground(new Color(60,63,65));
        txtmail.setForeground(new Color(60,63,65));
    }//GEN-LAST:event_txtcountryFocusGained

    private void txtpassportFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtpassportFocusGained
        // TODO add your handling code here:
        lblpassport.setForeground(new Color(0,51,153));
        jSeparator1.setBackground(new Color(0,51,153));
        jSeparator2.setForeground(new Color(60,63,65));
        jSeparator3.setForeground(new Color(60,63,65));
        jSeparator4.setForeground(new Color(60,63,65));
        jSeparator5.setForeground(new Color(60,63,65));
        jSeparator6.setForeground(new Color(60,63,65));
        lblcountry.setForeground(new Color(60,63,65));
        lblnic.setForeground(new Color(60,63,65));
        lblfn.setForeground(new Color(60,63,65));
        lblmail.setForeground(new Color(60,63,65));
         lblcountry.setForeground(new Color(60,63,65));
        txtpassport.setForeground(new Color(0,51,153));
        txtln.setForeground(new Color(60,63,65));
        txtcountry.setForeground(new Color(60,63,65));
        txtnic.setForeground(new Color(60,63,65));
        txtfn.setForeground(new Color(60,63,65));
        txtln.setForeground(new Color(60,63,65));

    }//GEN-LAST:event_txtpassportFocusGained

    private void txtmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtmailFocusGained
        // TODO add your handling code here:
         lblmail.setForeground(new Color(0,51,153));
        jSeparator6.setBackground(new Color(0,51,153));
        jSeparator2.setForeground(new Color(60,63,65));
        jSeparator3.setForeground(new Color(60,63,65));
        jSeparator4.setForeground(new Color(60,63,65));
        jSeparator5.setForeground(new Color(60,63,65));
        jSeparator1.setForeground(new Color(60,63,65));
        lblfn.setForeground(new Color(60,63,65));
        lblln.setForeground(new Color(60,63,65));
        lblnic.setForeground(new Color(60,63,65));
        lblpassport.setForeground(new Color(60,63,65));
        lblcountry.setForeground(new Color(60,63,65));
        txtmail.setForeground(new Color(0,51,153));
        txtln.setForeground(new Color(60,63,65));
        txtnic.setForeground(new Color(60,63,65));
        txtpassport.setForeground(new Color(60,63,65));
        txtfn.setForeground(new Color(60,63,65));
        txtcountry.setForeground(new Color(60,63,65));

    }//GEN-LAST:event_txtmailFocusGained

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
          Traveller_2 t1=new Traveller_2();
        t1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Home t2=new  Home();
        t2.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Traveller_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Traveller_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Traveller_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Traveller_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Traveller_1().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JLabel lblcountry;
    private javax.swing.JLabel lblexit1;
    private javax.swing.JLabel lblfn;
    private javax.swing.JLabel lblln;
    private javax.swing.JLabel lblmail;
    private javax.swing.JLabel lblnic;
    private javax.swing.JLabel lblpassport;
    private javax.swing.JTextField txtcountry;
    private javax.swing.JTextField txtfn;
    private javax.swing.JTextField txtln;
    private javax.swing.JTextField txtmail;
    private javax.swing.JTextField txtnic;
    private javax.swing.JTextField txtpassport;
    // End of variables declaration//GEN-END:variables
}
